In [43]:
import pandas as pd
import numpy as np

In [44]:
file_path = "../data/raw/ADS_GY_Equity_RAW_EXPORT.csv"

In [45]:
df = pd.read_csv(file_path, header=None)

df.head(15)

,0,1,2,3,4,5,6,7,8,9
0,Bloomberg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ADS GY Equity - ADIDAS AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Income Statement | Standardized | Peri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Currency: EUR Units: Millions (except p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,*** SYNTHETIC SAMPLE DATA - GENERATED FOR CLAS...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,In Millions of EUR except Per Share,NaN,FY 2016,FY 2017,FY 2018,FY 2019,FY 2020,FY 2021,FY 2022,FY 2023
7,NaN,NaN,12/31/2016,12/31/2017,12/31/2018,12/31/2019,12/31/2020,12/31/2021,12/31/2022,12/31/2023
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Wholesale,NaN,"11,663.00","12,943.00","12,733.00","13,191.00","10,160.00","11,148.00","12,156.00","11,142.00"
11,Retail,NaN,"5,841.00","7,172.00","8,196.00","9,480.00","8,970.00","9,428.00","9,725.00","9,706.00"
12,Other Businesses,-2.0,979,"1,103.00","9,86,000",969,714,658,630,579
13,Total Net Revenue,NaN,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"
14,Revenue Growth Y/Y,NaN,NM,14.80%,3.30%,7.90%,-16.10%,7.00%,6.00%,-4.80%

In [46]:
header=None

In [47]:
print(df.shape)

(57, 10)

In [48]:
df.head(15)

,0,1,2,3,4,5,6,7,8,9
0,Bloomberg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ADS GY Equity - ADIDAS AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Income Statement | Standardized | Peri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Currency: EUR Units: Millions (except p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,*** SYNTHETIC SAMPLE DATA - GENERATED FOR CLAS...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,In Millions of EUR except Per Share,NaN,FY 2016,FY 2017,FY 2018,FY 2019,FY 2020,FY 2021,FY 2022,FY 2023
7,NaN,NaN,12/31/2016,12/31/2017,12/31/2018,12/31/2019,12/31/2020,12/31/2021,12/31/2022,12/31/2023
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Wholesale,NaN,"11,663.00","12,943.00","12,733.00","13,191.00","10,160.00","11,148.00","12,156.00","11,142.00"
11,Retail,NaN,"5,841.00","7,172.00","8,196.00","9,480.00","8,970.00","9,428.00","9,725.00","9,706.00"
12,Other Businesses,-2.0,979,"1,103.00","9,86,000",969,714,658,630,579
13,Total Net Revenue,NaN,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"
14,Revenue Growth Y/Y,NaN,NM,14.80%,3.30%,7.90%,-16.10%,7.00%,6.00%,-4.80%

In [49]:
pd.read_csv(file_path, header=None)

,0,1,2,3,4,5,6,7,8,9
0,Bloomberg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ADS GY Equity - ADIDAS AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Income Statement | Standardized | Peri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Currency: EUR Units: Millions (except p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,*** SYNTHETIC SAMPLE DATA - GENERATED FOR CLAS...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,In Millions of EUR except Per Share,NaN,FY 2016,FY 2017,FY 2018,FY 2019,FY 2020,FY 2021,FY 2022,FY 2023
7,NaN,NaN,12/31/2016,12/31/2017,12/31/2018,12/31/2019,12/31/2020,12/31/2021,12/31/2022,12/31/2023
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Wholesale,NaN,"11,663.00","12,943.00","12,733.00","13,191.00","10,160.00","11,148.00","12,156.00","11,142.00"
11,Retail,NaN,"5,841.00","7,172.00","8,196.00","9,480.00","8,970.00","9,428.00","9,725.00","9,706.00"
12,Other Businesses,-2.0,979,"1,103.00","9,86,000",969,714,658,630,579
13,Total Net Revenue,NaN,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"
14,Revenue Growth Y/Y,NaN,NM,14.80%,3.30%,7.90%,-16.10%,7.00%,6.00%,-4.80%
15,Total Net Revenue,NaN,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Cost of Goods Sold,NaN,"-9,500.00","-10,524.00","-10,607.00","-11,347.00","-9,982.00","-10,511.00","-11,863.00","-11,249.00"
18,GROSS PROFIT,NaN,"8,983.00","10,694.00","11,308.00","12,293.00","9,862.00","10,723.00","10,648.00","10,178.00"
19,Gross Margin %,NaN,48.60%,50.40%,51.60%,52.00%,49.70%,50.50%,47.30%,47.50%
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Royalty and Commission Income,NaN,108,115,121,130,96,104,112,107
22,Other Operating Income,NaN,60,66,71,78,52,58,63,55
23,Other Operating Expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Marketing and Point-of-Sale,NaN,"-2,532.00","-2,843.00","-2,871.00","-3,026.00","-2,361.00","-2,569.00","-2,791.00","-2,636.00"
25,Distribution and Selling Expense,NaN,"-4,029.00","-4,710.00","-4,909.00","-5,272.00","-5,358.00","-4,969.00","-5,470.00","-5,528.00"
26,General & Administration,NaN,-998,"-1,125.00","-1,140.00","-1,347.00","-1,290.00","-1,295.00","-1,756.00","-1,564.00"
27,Sundry Expenses,NaN,-185,-212,-219,-236,-198,-212,-225,-257
28,Total Other Operating Exp.,NaN,"-7,744.00","-8,890.00","-9,139.00","-9,881.00","-9,207.00","-9,045.00","-10,242.00","-9,985.00"
29,Goodwill / Intangible Impairment,NaN,—,—,—,—,—,—,-194,—
30,OPERATING PROFIT (EBIT),NaN,"1,407.00","1,985.00","2,361.00","2,620.00",803,"1,840.00",387,355
31,Operating Margin %,NaN,7.60%,9.40%,10.80%,11.10%,4.00%,8.70%,1.70%,1.70%
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Financial Income,NaN,20,24,28,32,26,30,44,62
34,Financial Expenses,-3.0,-74,-82,-91,-166,-178,-172,-199,-242
35,Income Before Taxes,NaN,"1,353.00","1,927.00","2,298.00","2,486.00",651,"1,698.00",232,175
36,Income Tax Expense,NaN,-392,-540,-597,-622,-228,-475,-174,-201
37,Effective Tax Rate %,NaN,29.00%,28.00%,26.00%,25.00%,35.00%,28.00%,75.00%,114.90%
38,Net Income from Continuing Ops.,NaN,961,"1,387.00","1,701.00","1,864.00",423,"1,223.00",58,-26
39,Net Income from Disc. Operations,-1.0,NaN,—,NaN,—,-70,232,NaN,—
40,Net Income (Total),NaN,961,"1,387.00","1,701.00","1,864.00",353,"1,455.00",58,-26
41,Less: Minority Interest,NaN,-12,-14,-11,-9,-6,-8,-8,-7
42,NET INCOME ATTRIB. TO SHAREHOLDERS,NaN,949,"1,373.00","1,690.00","1,855.00",347,"1,447.00",50,-33
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Basic EPS,NaN,4.72,6.78,8.45,9.48,1.79,7.39,0.27,-0.18
45,Diluted EPS,NaN,4.7,6.75,8.42,9.44,1.78,7.36,0.27,-0.18
46,Wtd. Avg Shares - Basic (mn),NaN,201,202.5,200,195.7,194.3,195.8,183.5,178.6
47,Wtd. Avg Shares - Diluted (mn),NaN,201.8,203.3,200.8,196.5,195.1,196.6,184.2,179.3
48,Dividend Per Share (DPS),NaN,2,2.6,3.35,3.85,—,3.3,0.7,0.7
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Source: Bloomberg Standardized Financials ---...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,(1) FY2021 reflects Reebok operations presente...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,(2) Value shown as extracted from the terminal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,(3) FY2019 onward reflects IFRS 16 lease accou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NM = not meaningful. #N/A N/A = field not av...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,These figures are synthetic training data and ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
for i, value in enumerate(df[0]):
    print(i, "→", value)

0 → Bloomberg
1 → ADS GY Equity     -     ADIDAS AG
2 → Income Statement   |   Standardized   |   Periodicity: Fiscal Year
3 → Currency: EUR        Units: Millions (except per share)        FYE: 31 December
4 → *** SYNTHETIC SAMPLE DATA - GENERATED FOR CLASSROOM TRAINING. NOT ACTUAL BLOOMBERG OUTPUT. ***
5 → nan
6 → In Millions of EUR except Per Share
7 → nan
8 → nan
9 → Revenue
10 →      Wholesale
11 →      Retail
12 →      Other  Businesses
13 →   Total Net Revenue
14 →   Revenue Growth  Y/Y
15 →   Total Net Revenue
16 → nan
17 →   Cost of Goods Sold
18 →   GROSS PROFIT
19 →   Gross Margin %
20 → nan
21 →   Royalty and Commission Income
22 →   Other Operating Income
23 →   Other Operating Expenses
24 →         Marketing and Point-of-Sale
25 →         Distribution and Selling Expense
26 →         General & Administration
27 →         Sundry Expenses
28 →   Total Other Operating Exp.
29 →   Goodwill / Intangible Impairment
30 →   OPERATING PROFIT (EBIT)
31 →   Operating Margin %
32 → nan
33 →   Financial Income
34 →   Financial Expenses
35 →   Income Before Taxes
36 →   Income Tax Expense
37 →   Effective Tax Rate %
38 →   Net Income from Continuing Ops.
39 →   Net Income from Disc. Operations
40 →   Net Income (Total)
41 →   Less: Minority Interest
42 →   NET INCOME ATTRIB. TO SHAREHOLDERS
43 → nan
44 →   Basic EPS
45 →   Diluted EPS
46 →   Wtd. Avg Shares - Basic (mn)
47 →   Wtd. Avg Shares - Diluted (mn)
48 →   Dividend Per Share (DPS)
49 → nan
50 → nan
51 → Source: Bloomberg Standardized Financials  ---  SYNTHETIC SAMPLE, generated for classroom use.
52 → (1) FY2021 reflects Reebok operations presented as discontinued operations; FY2020 restated on the same basis. Earlier years not restated.
53 → (2) Value shown as extracted from the terminal; confirm the reporting unit against the sheet header before use.
54 → (3) FY2019 onward reflects IFRS 16 lease accounting. Prior years are not restated.
55 → NM = not meaningful.   #N/A N/A = field not available for this period.   — = nil or not reported.
56 → These figures are synthetic training data and must not be presented as actual company results.

In [51]:
# Separate the select data 
df.iloc[6:16]

,0,1,2,3,4,5,6,7,8,9
6,In Millions of EUR except Per Share,NaN,FY 2016,FY 2017,FY 2018,FY 2019,FY 2020,FY 2021,FY 2022,FY 2023
7,NaN,NaN,12/31/2016,12/31/2017,12/31/2018,12/31/2019,12/31/2020,12/31/2021,12/31/2022,12/31/2023
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Wholesale,NaN,"11,663.00","12,943.00","12,733.00","13,191.00","10,160.00","11,148.00","12,156.00","11,142.00"
11,Retail,NaN,"5,841.00","7,172.00","8,196.00","9,480.00","8,970.00","9,428.00","9,725.00","9,706.00"
12,Other Businesses,-2.0,979,"1,103.00","9,86,000",969,714,658,630,579
13,Total Net Revenue,NaN,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"
14,Revenue Growth Y/Y,NaN,NM,14.80%,3.30%,7.90%,-16.10%,7.00%,6.00%,-4.80%
15,Total Net Revenue,NaN,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"

In [52]:
# Here we are selecting the rows from index 9 to 52 (inclusive) and the columns at index 0, 2, 3, 4, 5, 6, 7, 8, and 9. This will give us a subset of the DataFrame with the specified rows and columns.

df.iloc[9:53, [0, 2, 3, 4, 5, 6, 7, 8, 9]]

,0,2,3,4,5,6,7,8,9
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Wholesale,"11,663.00","12,943.00","12,733.00","13,191.00","10,160.00","11,148.00","12,156.00","11,142.00"
11,Retail,"5,841.00","7,172.00","8,196.00","9,480.00","8,970.00","9,428.00","9,725.00","9,706.00"
12,Other Businesses,979,"1,103.00","9,86,000",969,714,658,630,579
13,Total Net Revenue,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"
14,Revenue Growth Y/Y,NM,14.80%,3.30%,7.90%,-16.10%,7.00%,6.00%,-4.80%
15,Total Net Revenue,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Cost of Goods Sold,"-9,500.00","-10,524.00","-10,607.00","-11,347.00","-9,982.00","-10,511.00","-11,863.00","-11,249.00"
18,GROSS PROFIT,"8,983.00","10,694.00","11,308.00","12,293.00","9,862.00","10,723.00","10,648.00","10,178.00"
19,Gross Margin %,48.60%,50.40%,51.60%,52.00%,49.70%,50.50%,47.30%,47.50%
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Royalty and Commission Income,108,115,121,130,96,104,112,107
22,Other Operating Income,60,66,71,78,52,58,63,55
23,Other Operating Expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Marketing and Point-of-Sale,"-2,532.00","-2,843.00","-2,871.00","-3,026.00","-2,361.00","-2,569.00","-2,791.00","-2,636.00"
25,Distribution and Selling Expense,"-4,029.00","-4,710.00","-4,909.00","-5,272.00","-5,358.00","-4,969.00","-5,470.00","-5,528.00"
26,General & Administration,-998,"-1,125.00","-1,140.00","-1,347.00","-1,290.00","-1,295.00","-1,756.00","-1,564.00"
27,Sundry Expenses,-185,-212,-219,-236,-198,-212,-225,-257
28,Total Other Operating Exp.,"-7,744.00","-8,890.00","-9,139.00","-9,881.00","-9,207.00","-9,045.00","-10,242.00","-9,985.00"
29,Goodwill / Intangible Impairment,—,—,—,—,—,—,-194,—
30,OPERATING PROFIT (EBIT),"1,407.00","1,985.00","2,361.00","2,620.00",803,"1,840.00",387,355
31,Operating Margin %,7.60%,9.40%,10.80%,11.10%,4.00%,8.70%,1.70%,1.70%
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Financial Income,20,24,28,32,26,30,44,62
34,Financial Expenses,-74,-82,-91,-166,-178,-172,-199,-242
35,Income Before Taxes,"1,353.00","1,927.00","2,298.00","2,486.00",651,"1,698.00",232,175
36,Income Tax Expense,-392,-540,-597,-622,-228,-475,-174,-201
37,Effective Tax Rate %,29.00%,28.00%,26.00%,25.00%,35.00%,28.00%,75.00%,114.90%
38,Net Income from Continuing Ops.,961,"1,387.00","1,701.00","1,864.00",423,"1,223.00",58,-26
39,Net Income from Disc. Operations,NaN,—,NaN,—,-70,232,NaN,—
40,Net Income (Total),961,"1,387.00","1,701.00","1,864.00",353,"1,455.00",58,-26
41,Less: Minority Interest,-12,-14,-11,-9,-6,-8,-8,-7
42,NET INCOME ATTRIB. TO SHAREHOLDERS,949,"1,373.00","1,690.00","1,855.00",347,"1,447.00",50,-33
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Basic EPS,4.72,6.78,8.45,9.48,1.79,7.39,0.27,-0.18
45,Diluted EPS,4.7,6.75,8.42,9.44,1.78,7.36,0.27,-0.18
46,Wtd. Avg Shares - Basic (mn),201,202.5,200,195.7,194.3,195.8,183.5,178.6
47,Wtd. Avg Shares - Diluted (mn),201.8,203.3,200.8,196.5,195.1,196.6,184.2,179.3
48,Dividend Per Share (DPS),2,2.6,3.35,3.85,—,3.3,0.7,0.7
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Source: Bloomberg Standardized Financials ---...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,(1) FY2021 reflects Reebok operations presente...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df.iloc[45:57]

,0,1,2,3,4,5,6,7,8,9
45,Diluted EPS,NaN,4.7,6.75,8.42,9.44,1.78,7.36,0.27,-0.18
46,Wtd. Avg Shares - Basic (mn),NaN,201,202.5,200,195.7,194.3,195.8,183.5,178.6
47,Wtd. Avg Shares - Diluted (mn),NaN,201.8,203.3,200.8,196.5,195.1,196.6,184.2,179.3
48,Dividend Per Share (DPS),NaN,2,2.6,3.35,3.85,—,3.3,0.7,0.7
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Source: Bloomberg Standardized Financials ---...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,(1) FY2021 reflects Reebok operations presente...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,(2) Value shown as extracted from the terminal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,(3) FY2019 onward reflects IFRS 16 lease accou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NM = not meaningful. #N/A N/A = field not av...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,These figures are synthetic training data and ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
financial_df = df.iloc[9:49].copy()

financial_df.head()

,0,1,2,3,4,5,6,7,8,9
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Wholesale,NaN,"11,663.00","12,943.00","12,733.00","13,191.00","10,160.00","11,148.00","12,156.00","11,142.00"
11,Retail,NaN,"5,841.00","7,172.00","8,196.00","9,480.00","8,970.00","9,428.00","9,725.00","9,706.00"
12,Other Businesses,-2.0,979,"1,103.00","9,86,000",969,714,658,630,579
13,Total Net Revenue,NaN,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"

In [55]:
financial_df = financial_df.iloc[:, [0, 2, 3, 4, 5, 6, 7, 8, 9]]

In [56]:
financial_df.columns = [
    "Line Item",
    "FY2016",
    "FY2017",
    "FY2018",
    "FY2019",
    "FY2020",
    "FY2021",
    "FY2022",
    "FY2023"
]

financial_df.head()

,Line Item,FY2016,FY2017,FY2018,FY2019,FY2020,FY2021,FY2022,FY2023
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Wholesale,"11,663.00","12,943.00","12,733.00","13,191.00","10,160.00","11,148.00","12,156.00","11,142.00"
11,Retail,"5,841.00","7,172.00","8,196.00","9,480.00","8,970.00","9,428.00","9,725.00","9,706.00"
12,Other Businesses,979,"1,103.00","9,86,000",969,714,658,630,579
13,Total Net Revenue,"18,483.00","21,218.00","21,915.00","23,640.00","19,844.00","21,234.00","22,511.00","21,427.00"

In [57]:
financial_df.dtypes

Line Item    str
FY2016       str
FY2017       str
FY2018       str
FY2019       str
FY2020       str
FY2021       str
FY2022       str
FY2023       str
dtype: object

In [58]:
def clean_value(value):
    if pd.isna(value):
        return np.nan
    
    value = str(value).strip()
    
    if value in ["NM", "N/A", "#N/A N/A", "—", "-", ""]:
        return np.nan
    
    if value.endswith("%"):
        return float(value.replace("%", "").replace(",", "").strip()) / 100
    
    if value.startswith("(") and value.endswith(")"):
        value = "-" + value[1:-1]
    
    value = value.replace(",", "").strip()
    
    return float(value)

In [59]:
test_values = [
    "11,663.00",
    "-9,500.00",
    "14.80%",
    "(392.00)",
    "NM",
    "—",
    "#N/A N/A"
]

for value in test_values:
    print(value, "→", clean_value(value))

11,663.00 → 11663.0
-9,500.00 → -9500.0
14.80% → 0.14800000000000002
(392.00) → -392.0
NM → nan
— → nan
#N/A N/A → nan

In [60]:
year_columns = [
    "FY2016", "FY2017", "FY2018", "FY2019",
    "FY2020", "FY2021", "FY2022", "FY2023"
]

for col in year_columns:
    financial_df[col] = financial_df[col].apply(clean_value)

In [61]:
financial_df.head(20)

,Line Item,FY2016,FY2017,FY2018,FY2019,FY2020,FY2021,FY2022,FY2023
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Wholesale,11663.000,12943.000,12733.000,13191.000,10160.000,11148.000,12156.000,11142.000
11,Retail,5841.000,7172.000,8196.000,9480.000,8970.000,9428.000,9725.000,9706.000
12,Other Businesses,979.000,1103.000,986000.000,969.000,714.000,658.000,630.000,579.000
13,Total Net Revenue,18483.000,21218.000,21915.000,23640.000,19844.000,21234.000,22511.000,21427.000
14,Revenue Growth Y/Y,NaN,0.148,0.033,0.079,-0.161,0.070,0.060,-0.048
15,Total Net Revenue,18483.000,21218.000,21915.000,23640.000,19844.000,21234.000,22511.000,21427.000
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Cost of Goods Sold,-9500.000,-10524.000,-10607.000,-11347.000,-9982.000,-10511.000,-11863.000,-11249.000
18,GROSS PROFIT,8983.000,10694.000,11308.000,12293.000,9862.000,10723.000,10648.000,10178.000
19,Gross Margin %,0.486,0.504,0.516,0.520,0.497,0.505,0.473,0.475
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Royalty and Commission Income,108.000,115.000,121.000,130.000,96.000,104.000,112.000,107.000
22,Other Operating Income,60.000,66.000,71.000,78.000,52.000,58.000,63.000,55.000
23,Other Operating Expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Marketing and Point-of-Sale,-2532.000,-2843.000,-2871.000,-3026.000,-2361.000,-2569.000,-2791.000,-2636.000
25,Distribution and Selling Expense,-4029.000,-4710.000,-4909.000,-5272.000,-5358.000,-4969.000,-5470.000,-5528.000
26,General & Administration,-998.000,-1125.000,-1140.000,-1347.000,-1290.000,-1295.000,-1756.000,-1564.000
27,Sundry Expenses,-185.000,-212.000,-219.000,-236.000,-198.000,-212.000,-225.000,-257.000
28,Total Other Operating Exp.,-7744.000,-8890.000,-9139.000,-9881.000,-9207.000,-9045.000,-10242.000,-9985.000

In [62]:
financial_df.dtypes

Line Item        str
FY2016       float64
FY2017       float64
FY2018       float64
FY2019       float64
FY2020       float64
FY2021       float64
FY2022       float64
FY2023       float64
dtype: object

In [63]:
financial_df.isna().sum()

Line Item    4
FY2016       9
FY2017       8
FY2018       8
FY2019       8
FY2020       8
FY2021       7
FY2022       7
FY2023       8
dtype: int64

In [64]:
financial_df[financial_df.isna().any(axis=1)]

,Line Item,FY2016,FY2017,FY2018,FY2019,FY2020,FY2021,FY2022,FY2023
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Revenue Growth Y/Y,NaN,0.148,0.033,0.079,-0.161,0.07,0.06,-0.048
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Other Operating Expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Goodwill / Intangible Impairment,NaN,NaN,NaN,NaN,NaN,NaN,-194.00,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Net Income from Disc. Operations,NaN,NaN,NaN,NaN,-70.000,232.00,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Dividend Per Share (DPS),2.0,2.600,3.350,3.850,NaN,3.30,0.70,0.700

In [65]:
df.loc[43]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: 43, dtype: object

In [66]:
financial_df[financial_df["Line Item"].isna()]

   Line Item  FY2016  FY2017  FY2018  FY2019  FY2020  FY2021  FY2022  FY2023
16       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
20       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
32       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
43       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

In [67]:
financial_df = financial_df.dropna(subset=["Line Item"]).copy()

In [68]:
financial_df.shape

(36, 9)

In [69]:
financial_df.head()

,Line Item,FY2016,FY2017,FY2018,FY2019,FY2020,FY2021,FY2022,FY2023
9,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Wholesale,11663.0,12943.0,12733.0,13191.0,10160.0,11148.0,12156.0,11142.0
11,Retail,5841.0,7172.0,8196.0,9480.0,8970.0,9428.0,9725.0,9706.0
12,Other Businesses,979.0,1103.0,986000.0,969.0,714.0,658.0,630.0,579.0
13,Total Net Revenue,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0

In [70]:
df.loc[12]

0         Other  Businesses
1                      -2.0
2                       979
3                  1,103.00
4                  9,86,000
5                       969
6                       714
7                       658
8                       630
9                       579
Name: 12, dtype: object

In [71]:
financial_df["Line Item"] = financial_df["Line Item"].str.strip()

In [74]:
wholesale_2018 = financial_df.loc[
    financial_df["Line Item"] == "Wholesale", "FY2018"
].iloc[0]

retail_2018 = financial_df.loc[
    financial_df["Line Item"] == "Retail", "FY2018"
].iloc[0]

other_2018 = financial_df.loc[
    financial_df["Line Item"] == "Other Businesses", "FY2018"
].iloc[0]

total_revenue_2018 = financial_df.loc[
    financial_df["Line Item"] == "Total Net Revenue", "FY2018"
].iloc[0]

print("Wholesale:", wholesale_2018)
print("Retail:", retail_2018)
print("Other Businesses:", other_2018)
print("Reported Total Revenue:", total_revenue_2018)
print("Calculated Total:", wholesale_2018 + retail_2018 + other_2018)

IndexError: single positional indexer is out-of-bounds

In [73]:
financial_df.loc[financial_df["Line Item"].str.contains("Other", na=False), "Line Item"].apply(repr)

12             'Other  Businesses'
22        'Other Operating Income'
23      'Other Operating Expenses'
28    'Total Other Operating Exp.'
Name: Line Item, dtype: str

In [75]:
financial_df["Line Item"] = (
    financial_df["Line Item"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [76]:
wholesale_2018 = financial_df.loc[
    financial_df["Line Item"] == "Wholesale", "FY2018"
].iloc[0]

retail_2018 = financial_df.loc[
    financial_df["Line Item"] == "Retail", "FY2018"
].iloc[0]

other_2018 = financial_df.loc[
    financial_df["Line Item"] == "Other Businesses", "FY2018"
].iloc[0]

total_revenue_2018 = financial_df.loc[
    financial_df["Line Item"] == "Total Net Revenue", "FY2018"
].iloc[0]

print("Wholesale:", wholesale_2018)
print("Retail:", retail_2018)
print("Other Businesses:", other_2018)
print("Reported Total Revenue:", total_revenue_2018)
print("Calculated Total:", wholesale_2018 + retail_2018 + other_2018)

Wholesale: 12733.0
Retail: 8196.0
Other Businesses: 986000.0
Reported Total Revenue: 21915.0
Calculated Total: 1006929.0

In [77]:
financial_df.loc[
    financial_df["Line Item"] == "Other Businesses",
    "FY2018"
] = 986

In [78]:
other_2018 = financial_df.loc[
    financial_df["Line Item"] == "Other Businesses",
    "FY2018"
].iloc[0]

print("Corrected Other Businesses:", other_2018)

Corrected Other Businesses: 986.0

In [79]:
calculated_total = (
    wholesale_2018
    + retail_2018
    + other_2018
)

print("Reported Total Revenue:", total_revenue_2018)
print("Calculated Total:", calculated_total)
print("Reconciled:", calculated_total == total_revenue_2018)

Reported Total Revenue: 21915.0
Calculated Total: 21915.0
Reconciled: True

In [80]:
financial_df.to_csv(
    "../data/cleaned/Bloomberg_PL_Cleaned.csv",
    index=False
)

In [81]:
import os

os.makedirs("../data/cleaned", exist_ok=True)

In [82]:
financial_df.to_csv(
    "../data/cleaned/Bloomberg_PL_Cleaned.csv",
    index=False
)

In [83]:
financial_df.loc[
    financial_df["Line Item"].isin([
        "Total Net Revenue",
        "Cost of Goods Sold",
        "GROSS PROFIT"
    ]),
    ["Line Item", "FY2016", "FY2017", "FY2018", "FY2019",
     "FY2020", "FY2021", "FY2022", "FY2023"]
]

,Line Item,FY2016,FY2017,FY2018,FY2019,FY2020,FY2021,FY2022,FY2023
13,Total Net Revenue,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0
15,Total Net Revenue,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0
17,Cost of Goods Sold,-9500.0,-10524.0,-10607.0,-11347.0,-9982.0,-10511.0,-11863.0,-11249.0
18,GROSS PROFIT,8983.0,10694.0,11308.0,12293.0,9862.0,10723.0,10648.0,10178.0

In [84]:
revenue = financial_df.loc[
    financial_df["Line Item"] == "Total Net Revenue",
    "FY2016":"FY2023"
].iloc[0]

cogs = financial_df.loc[
    financial_df["Line Item"] == "Cost of Goods Sold",
    "FY2016":"FY2023"
].iloc[0]

reported_gross_profit = financial_df.loc[
    financial_df["Line Item"] == "GROSS PROFIT",
    "FY2016":"FY2023"
].iloc[0]

calculated_gross_profit = revenue + cogs

print("Calculated Gross Profit:")
print(calculated_gross_profit)

print("\nReported Gross Profit:")
print(reported_gross_profit)

print("\nReconciled:")
print(calculated_gross_profit.round(2).equals(
    reported_gross_profit.round(2)
))

Calculated Gross Profit:
FY2016     8983.0
FY2017    10694.0
FY2018    11308.0
FY2019    12293.0
FY2020     9862.0
FY2021    10723.0
FY2022    10648.0
FY2023    10178.0
dtype: float64

Reported Gross Profit:
FY2016     8983.0
FY2017    10694.0
FY2018    11308.0
FY2019    12293.0
FY2020     9862.0
FY2021    10723.0
FY2022    10648.0
FY2023    10178.0
Name: 18, dtype: float64

Reconciled:
True

In [85]:
gross_profit = financial_df.loc[
    financial_df["Line Item"] == "GROSS PROFIT",
    "FY2016":"FY2023"
].iloc[0]

royalty_income = financial_df.loc[
    financial_df["Line Item"] == "Royalty and Commission Income",
    "FY2016":"FY2023"
].iloc[0]

other_operating_income = financial_df.loc[
    financial_df["Line Item"] == "Other Operating Income",
    "FY2016":"FY2023"
].iloc[0]

other_operating_expenses = financial_df.loc[
    financial_df["Line Item"] == "Total Other Operating Exp.",
    "FY2016":"FY2023"
].iloc[0]

impairment = financial_df.loc[
    financial_df["Line Item"] == "Goodwill / Intangible Impairment",
    "FY2016":"FY2023"
].iloc[0]

reported_ebit = financial_df.loc[
    financial_df["Line Item"] == "OPERATING PROFIT (EBIT)",
    "FY2016":"FY2023"
].iloc[0]

In [86]:
calculated_ebit = (
    gross_profit
    + royalty_income
    + other_operating_income
    + other_operating_expenses
    + impairment.fillna(0)
)

print("Calculated EBIT:")
print(calculated_ebit)

print("\nReported EBIT:")
print(reported_ebit)

print("\nReconciled:")
print(calculated_ebit.round(2).equals(
    reported_ebit.round(2)
))

Calculated EBIT:
FY2016    1407.0
FY2017    1985.0
FY2018    2361.0
FY2019    2620.0
FY2020     803.0
FY2021    1840.0
FY2022     387.0
FY2023     355.0
dtype: float64

Reported EBIT:
FY2016    1407.0
FY2017    1985.0
FY2018    2361.0
FY2019    2620.0
FY2020     803.0
FY2021    1840.0
FY2022     387.0
FY2023     355.0
Name: 30, dtype: float64

Reconciled:
True

In [87]:
net_income = financial_df.loc[
    financial_df["Line Item"] == "Net Income Attributable to Shareholders",
    "FY2016":"FY2023"
].iloc[0]

shares = financial_df.loc[
    financial_df["Line Item"] == "Wtd. Avg Shares - Basic (mn)",
    "FY2016":"FY2023"
].iloc[0]

reported_eps = financial_df.loc[
    financial_df["Line Item"] == "Basic EPS",
    "FY2016":"FY2023"
].iloc[0]

calculated_eps = net_income / shares

print("Calculated EPS:")
print(calculated_eps)

print("\nReported EPS:")
print(reported_eps)

print("\nReconciled:")
print(calculated_eps.round(2).equals(
    reported_eps.round(2)
))

IndexError: single positional indexer is out-of-bounds

In [88]:
financial_df["Line Item"].tolist()

['Revenue',
 'Wholesale',
 'Retail',
 'Other Businesses',
 'Total Net Revenue',
 'Revenue Growth Y/Y',
 'Total Net Revenue',
 'Cost of Goods Sold',
 'GROSS PROFIT',
 'Gross Margin %',
 'Royalty and Commission Income',
 'Other Operating Income',
 'Other Operating Expenses',
 'Marketing and Point-of-Sale',
 'Distribution and Selling Expense',
 'General & Administration',
 'Sundry Expenses',
 'Total Other Operating Exp.',
 'Goodwill / Intangible Impairment',
 'OPERATING PROFIT (EBIT)',
 'Operating Margin %',
 'Financial Income',
 'Financial Expenses',
 'Income Before Taxes',
 'Income Tax Expense',
 'Effective Tax Rate %',
 'Net Income from Continuing Ops.',
 'Net Income from Disc. Operations',
 'Net Income (Total)',
 'Less: Minority Interest',
 'NET INCOME ATTRIB. TO SHAREHOLDERS',
 'Basic EPS',
 'Diluted EPS',
 'Wtd. Avg Shares - Basic (mn)',
 'Wtd. Avg Shares - Diluted (mn)',
 'Dividend Per Share (DPS)']

In [89]:
financial_df[
    financial_df["Line Item"].str.contains("Net", case=False, na=False)
]["Line Item"].tolist()

['Total Net Revenue',
 'Total Net Revenue',
 'Net Income from Continuing Ops.',
 'Net Income from Disc. Operations',
 'Net Income (Total)',
 'NET INCOME ATTRIB. TO SHAREHOLDERS']

In [90]:
financial_df["Line Item"] == "Net Income Attributable to Shareholders"

9     False
10    False
11    False
12    False
13    False
14    False
15    False
17    False
18    False
19    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
44    False
45    False
46    False
47    False
48    False
Name: Line Item, dtype: bool

In [91]:
financial_df[
    financial_df["Line Item"].str.contains("Net", case=False, na=False)
]["Line Item"].tolist()

['Total Net Revenue',
 'Total Net Revenue',
 'Net Income from Continuing Ops.',
 'Net Income from Disc. Operations',
 'Net Income (Total)',
 'NET INCOME ATTRIB. TO SHAREHOLDERS']

In [92]:
net_income = financial_df.loc[
    financial_df["Line Item"] == "NET INCOME ATTRIB. TO SHAREHOLDERS",
    ["FY2016","FY2023"]
].iloc[0]

shares = financial_df.loc[
    financial_df["Line Item"] == "Wtd. Avg Shares - Basic (mn)",
    ["FY2016","FY2023"]
].iloc[0]

reported_eps = financial_df.loc[
    financial_df["Line Item"] == "Basic EPS",
    ["FY2016","FY2023"]
].iloc[0]

calculated_eps = net_income / shares

print("Calculated EPS:")
print(calculated_eps)

print("\nReported EPS:")
print(reported_eps)

print("\nReconciled:")
print(calculated_eps.round(2).equals(reported_eps.round(2)))

Calculated EPS:
FY2016    4.721393
FY2023   -0.184770
dtype: float64

Reported EPS:
FY2016    4.72
FY2023   -0.18
Name: 44, dtype: float64

Reconciled:
True

In [93]:
long_df = financial_df.melt(
    id_vars="Line Item",
    var_name="Fiscal Year",
    value_name="Value"
)

long_df.head(15)

                           Line Item Fiscal Year      Value
0                            Revenue      FY2016        NaN
1                          Wholesale      FY2016  11663.000
2                             Retail      FY2016   5841.000
3                   Other Businesses      FY2016    979.000
4                  Total Net Revenue      FY2016  18483.000
5                 Revenue Growth Y/Y      FY2016        NaN
6                  Total Net Revenue      FY2016  18483.000
7                 Cost of Goods Sold      FY2016  -9500.000
8                       GROSS PROFIT      FY2016   8983.000
9                     Gross Margin %      FY2016      0.486
10     Royalty and Commission Income      FY2016    108.000
11            Other Operating Income      FY2016     60.000
12          Other Operating Expenses      FY2016        NaN
13       Marketing and Point-of-Sale      FY2016  -2532.000
14  Distribution and Selling Expense      FY2016  -4029.000

In [94]:
long_df.shape

(288, 3)

In [95]:
long_df.dtypes

Line Item          str
Fiscal Year        str
Value          float64
dtype: object

In [96]:
long_df = long_df.dropna(subset=["Value"]).copy()

In [97]:
long_df.shape

(257, 3)

In [98]:
long_df.head(15)

                           Line Item Fiscal Year      Value
1                          Wholesale      FY2016  11663.000
2                             Retail      FY2016   5841.000
3                   Other Businesses      FY2016    979.000
4                  Total Net Revenue      FY2016  18483.000
6                  Total Net Revenue      FY2016  18483.000
7                 Cost of Goods Sold      FY2016  -9500.000
8                       GROSS PROFIT      FY2016   8983.000
9                     Gross Margin %      FY2016      0.486
10     Royalty and Commission Income      FY2016    108.000
11            Other Operating Income      FY2016     60.000
13       Marketing and Point-of-Sale      FY2016  -2532.000
14  Distribution and Selling Expense      FY2016  -4029.000
15          General & Administration      FY2016   -998.000
16                   Sundry Expenses      FY2016   -185.000
17        Total Other Operating Exp.      FY2016  -7744.000

In [99]:
long_df.loc[
    (long_df["Line Item"] == "Other Businesses") &
    (long_df["Fiscal Year"] == "FY2018"),
    "Value"
] = 986

In [100]:
long_df[
    (long_df["Line Item"] == "Other Businesses") &
    (long_df["Fiscal Year"] == "FY2018")
]

           Line Item Fiscal Year  Value
75  Other Businesses      FY2018  986.0

In [101]:
print("Shape:", long_df.shape)
print("Missing values:")
print(long_df.isna().sum())
print("Duplicate rows:", long_df.duplicated().sum())
print("Data types:")
print(long_df.dtypes)

Shape: (257, 3)
Missing values:
Line Item      0
Fiscal Year    0
Value          0
dtype: int64
Duplicate rows: 8
Data types:
Line Item          str
Fiscal Year        str
Value          float64
dtype: object

In [102]:
long_df[long_df.duplicated(keep=False)].sort_values(
    ["Line Item", "Fiscal Year"]
)

             Line Item Fiscal Year    Value
4    Total Net Revenue      FY2016  18483.0
6    Total Net Revenue      FY2016  18483.0
40   Total Net Revenue      FY2017  21218.0
42   Total Net Revenue      FY2017  21218.0
76   Total Net Revenue      FY2018  21915.0
78   Total Net Revenue      FY2018  21915.0
112  Total Net Revenue      FY2019  23640.0
114  Total Net Revenue      FY2019  23640.0
148  Total Net Revenue      FY2020  19844.0
150  Total Net Revenue      FY2020  19844.0
184  Total Net Revenue      FY2021  21234.0
186  Total Net Revenue      FY2021  21234.0
220  Total Net Revenue      FY2022  22511.0
222  Total Net Revenue      FY2022  22511.0
256  Total Net Revenue      FY2023  21427.0
258  Total Net Revenue      FY2023  21427.0

In [103]:
long_df = long_df.drop_duplicates(
    subset=["Line Item", "Fiscal Year", "Value"]
).copy()

In [104]:
print("Shape:", long_df.shape)
print("Duplicate rows:", long_df.duplicated().sum())

Shape: (249, 3)
Duplicate rows: 0

In [105]:
long_df.to_csv(
    "../data/cleaned/Bloomberg_PL_Cleaned.csv",
    index=False
)

In [106]:
import os

os.path.exists("../data/cleaned/Bloomberg_PL_Cleaned.csv")

True

In [107]:
print(financial_df.shape)

(36, 9)

In [108]:
financial_df["Line Item"].unique()

<StringArray>
[                           'Revenue',                          'Wholesale',
                             'Retail',                   'Other Businesses',
                  'Total Net Revenue',                 'Revenue Growth Y/Y',
                 'Cost of Goods Sold',                       'GROSS PROFIT',
                     'Gross Margin %',      'Royalty and Commission Income',
             'Other Operating Income',           'Other Operating Expenses',
        'Marketing and Point-of-Sale',   'Distribution and Selling Expense',
           'General & Administration',                    'Sundry Expenses',
         'Total Other Operating Exp.',   'Goodwill / Intangible Impairment',
            'OPERATING PROFIT (EBIT)',                 'Operating Margin %',
                   'Financial Income',                 'Financial Expenses',
                'Income Before Taxes',                 'Income Tax Expense',
               'Effective Tax Rate %',    'Net Income from Continuing Ops.',
   'Net Income from Disc. Operations',                 'Net Income (Total)',
            'Less: Minority Interest', 'NET INCOME ATTRIB. TO SHAREHOLDERS',
                          'Basic EPS',                        'Diluted EPS',
       'Wtd. Avg Shares - Basic (mn)',     'Wtd. Avg Shares - Diluted (mn)',
           'Dividend Per Share (DPS)']
Length: 35, dtype: str

In [110]:
lookup_df = pd.read_excel(
    "../excel/Bloomberg_PL_Model.xlsx",
    sheet_name="Lookup"
)

lookup_df.head()

                         Line Item     Statement Group  Sign Conversion
0                         Basic EPS     EPS / Per Share        Per Share
1                Cost of Goods Sold                COGS         Negative
2                       Diluted EPS     EPS / Per Share        Per Share
3  Distribution and Selling Expense  Operating Expenses         Negative
4          Dividend Per Share (DPS)     EPS / Per Share        Per Share

In [111]:
set(financial_df["Line Item"].unique()) - set(lookup_df["Line Item"].unique())

KeyError: 'Line Item'

In [113]:
financial_df["Line Item"]

9                                Revenue
10                             Wholesale
11                                Retail
12                      Other Businesses
13                     Total Net Revenue
14                    Revenue Growth Y/Y
15                     Total Net Revenue
17                    Cost of Goods Sold
18                          GROSS PROFIT
19                        Gross Margin %
21         Royalty and Commission Income
22                Other Operating Income
23              Other Operating Expenses
24           Marketing and Point-of-Sale
25      Distribution and Selling Expense
26              General & Administration
27                       Sundry Expenses
28            Total Other Operating Exp.
29      Goodwill / Intangible Impairment
30               OPERATING PROFIT (EBIT)
31                    Operating Margin %
33                      Financial Income
34                    Financial Expenses
35                   Income Before Taxes
36                    Income Tax Expense
37                  Effective Tax Rate %
38       Net Income from Continuing Ops.
39      Net Income from Disc. Operations
40                    Net Income (Total)
41               Less: Minority Interest
42    NET INCOME ATTRIB. TO SHAREHOLDERS
44                             Basic EPS
45                           Diluted EPS
46          Wtd. Avg Shares - Basic (mn)
47        Wtd. Avg Shares - Diluted (mn)
48              Dividend Per Share (DPS)
Name: Line Item, dtype: str

In [114]:
set(long_df["Line Item"].unique()) - set(lookup_df["Line Item"].unique())

KeyError: 'Line Item'

In [115]:
print(long_df.columns.tolist())

['Line Item', 'Fiscal Year', 'Value']

In [116]:
financial_items = set(long_df["Line Item"].astype(str).str.strip())
lookup_items = set(lookup_df["Line Item"].astype(str).str.strip())

financial_items - lookup_items

KeyError: 'Line Item'

In [117]:
print(lookup_df.columns.tolist())

['Line Item ', 'Statement Group ', 'Sign Conversion ']

In [118]:
lookup_df.columns = lookup_df.columns.str.strip()

In [119]:
print(lookup_df.columns.tolist())

['Line Item', 'Statement Group', 'Sign Conversion']

In [120]:
financial_items = set(long_df["Line Item"].astype(str).str.strip())
lookup_items = set(lookup_df["Line Item"].astype(str).str.strip())

financial_items - lookup_items

set()

In [121]:
lookup_items - financial_items

{'Other Operating Expenses', 'Revenue'}

In [122]:
lookup_df.groupby(["Statement Group", "Sign Conversion"])["Line Item"].apply(list)

Statement Group     Sign Conversion
Below EBIT          Negative           [Financial Expenses, Income Tax Expense, Less:...
                    Percentage                                    [Effective Tax Rate %]
                    Positive                     [Financial Income, Income Before Taxes]
COGS                Negative                                        [Cost of Goods Sold]
EPS / Per Share     Per Share          [Basic EPS, Diluted EPS, Dividend Per Share (D...
Gross Profit        Positive                                              [GROSS PROFIT]
Growth              Percentage                                      [Revenue Growth Y/Y]
Margin              Percentage                      [Gross Margin %, Operating Margin %]
Net Income          Positive           [NET INCOME ATTRIB. TO SHAREHOLDERS, Net Incom...
Operating Expenses  Negative           [Distribution and Selling Expense, General & A...
Operating Income    Positive           [Other Operating Income, Royalty and Commissio...
Operating Profit    Positive                                   [OPERATING PROFIT (EBIT)]
Revenue             Positive           [Other Businesses, Retail, Total Net Revenue, ...
Share Data          Shares             [Wtd. Avg Shares - Basic (mn), Wtd. Avg Shares...
Name: Line Item, dtype: object

In [123]:
lookup_df.isna().sum()

Line Item          0
Statement Group    0
Sign Conversion    0
dtype: int64

In [124]:
lookup_df["Line Item"].duplicated().sum()

np.int64(0)

In [125]:
lookup_df.shape

(35, 3)

In [126]:
long_df.shape

(249, 3)

In [127]:
revenue_check = (
    long_df[long_df["Line Item"].isin(
        ["Wholesale", "Retail", "Other Businesses"]
    )]
    .groupby("Fiscal Year")["Value"]
    .sum()
)

total_revenue = (
    long_df[long_df["Line Item"] == "Total Net Revenue"]
    .set_index("Fiscal Year")["Value"]
)

revenue_check - total_revenue

Fiscal Year
FY2016    0.0
FY2017    0.0
FY2018    0.0
FY2019    0.0
FY2020    0.0
FY2021    0.0
FY2022    0.0
FY2023    0.0
Name: Value, dtype: float64

In [128]:
gross_profit_check = (
    long_df[long_df["Line Item"] == "Total Net Revenue"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Cost of Goods Sold"]
    .set_index("Fiscal Year")["Value"]
    -
    long_df[long_df["Line Item"] == "GROSS PROFIT"]
    .set_index("Fiscal Year")["Value"]
)

gross_profit_check

Fiscal Year
FY2016    0.0
FY2017    0.0
FY2018    0.0
FY2019    0.0
FY2020    0.0
FY2021    0.0
FY2022    0.0
FY2023    0.0
Name: Value, dtype: float64

In [129]:
ebit_check = (
    long_df[long_df["Line Item"] == "GROSS PROFIT"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Royalty and Commission Income"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Other Operating Income"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Marketing and Point-of-Sale"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Distribution and Selling Expense"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "General & Administration"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Sundry Expenses"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Goodwill / Intangible Impairment"]
    .set_index("Fiscal Year")["Value"]
    -
    long_df[long_df["Line Item"] == "OPERATING PROFIT (EBIT)"]
    .set_index("Fiscal Year")["Value"]
)

ebit_check

Fiscal Year
FY2016    NaN
FY2017    NaN
FY2018    NaN
FY2019    NaN
FY2020    NaN
FY2021    NaN
FY2022    0.0
FY2023    NaN
Name: Value, dtype: float64

In [130]:
ebit_items = [
    "GROSS PROFIT",
    "Royalty and Commission Income",
    "Other Operating Income",
    "Marketing and Point-of-Sale",
    "Distribution and Selling Expense",
    "General & Administration",
    "Sundry Expenses",
    "Goodwill / Intangible Impairment"
]

ebit_components = (
    long_df[long_df["Line Item"].isin(ebit_items)]
    .pivot_table(
        index="Fiscal Year",
        columns="Line Item",
        values="Value",
        aggfunc="sum",
        fill_value=0
    )
)

ebit_calculated = ebit_components.sum(axis=1)

ebit_actual = (
    long_df[long_df["Line Item"] == "OPERATING PROFIT (EBIT)"]
    .set_index("Fiscal Year")["Value"]
)

ebit_check = ebit_calculated - ebit_actual

ebit_check

Fiscal Year
FY2016    0.0
FY2017    0.0
FY2018    0.0
FY2019    0.0
FY2020    0.0
FY2021    0.0
FY2022    0.0
FY2023    0.0
dtype: float64

In [131]:
net_income_check = (
    long_df[long_df["Line Item"] == "Income Before Taxes"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Income Tax Expense"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Less: Minority Interest"]
    .set_index("Fiscal Year")["Value"]
    -
    long_df[long_df["Line Item"] == "Net Income (Total)"]
    .set_index("Fiscal Year")["Value"]
)

net_income_check

Fiscal Year
FY2016    -12.0
FY2017    -14.0
FY2018    -11.0
FY2019     -9.0
FY2020     64.0
FY2021   -240.0
FY2022     -8.0
FY2023     -7.0
Name: Value, dtype: float64

In [132]:
net_income_total_check = (
    long_df[long_df["Line Item"] == "Income Before Taxes"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Income Tax Expense"]
    .set_index("Fiscal Year")["Value"]
    -
    long_df[long_df["Line Item"] == "Net Income (Total)"]
    .set_index("Fiscal Year")["Value"]
)

net_income_total_check

Fiscal Year
FY2016      0.0
FY2017      0.0
FY2018      0.0
FY2019      0.0
FY2020     70.0
FY2021   -232.0
FY2022      0.0
FY2023      0.0
Name: Value, dtype: float64

In [133]:
net_income_total_check = (
    long_df[long_df["Line Item"] == "Income Before Taxes"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Income Tax Expense"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Net Income from Disc. Operations"]
    .set_index("Fiscal Year")["Value"].fillna(0)
    -
    long_df[long_df["Line Item"] == "Net Income (Total)"]
    .set_index("Fiscal Year")["Value"]
)

net_income_total_check

Fiscal Year
FY2016    NaN
FY2017    NaN
FY2018    NaN
FY2019    NaN
FY2020    0.0
FY2021    0.0
FY2022    NaN
FY2023    NaN
Name: Value, dtype: float64

In [134]:
years = sorted(long_df["Fiscal Year"].unique())

disc_ops = (
    long_df[long_df["Line Item"] == "Net Income from Disc. Operations"]
    .set_index("Fiscal Year")["Value"]
    .reindex(years, fill_value=0)
)

net_income_total_check = (
    long_df[long_df["Line Item"] == "Income Before Taxes"]
    .set_index("Fiscal Year")["Value"]
    +
    long_df[long_df["Line Item"] == "Income Tax Expense"]
    .set_index("Fiscal Year")["Value"]
    +
    disc_ops
    -
    long_df[long_df["Line Item"] == "Net Income (Total)"]
    .set_index("Fiscal Year")["Value"]
)

net_income_total_check

Fiscal Year
FY2016    0.0
FY2017    0.0
FY2018    0.0
FY2019    0.0
FY2020    0.0
FY2021    0.0
FY2022    0.0
FY2023    0.0
Name: Value, dtype: float64

In [135]:
basic_eps_check = (
    long_df[long_df["Line Item"] == "NET INCOME ATTRIB. TO SHAREHOLDERS"]
    .set_index("Fiscal Year")["Value"]
    /
    long_df[long_df["Line Item"] == "Wtd. Avg Shares - Basic (mn)"]
    .set_index("Fiscal Year")["Value"]
)

basic_eps_check

Fiscal Year
FY2016    4.721393
FY2017    6.780247
FY2018    8.450000
FY2019    9.478794
FY2020    1.785898
FY2021    7.390194
FY2022    0.272480
FY2023   -0.184770
Name: Value, dtype: float64

In [136]:
long_df.head()

            Line Item Fiscal Year    Value
1           Wholesale      FY2016  11663.0
2              Retail      FY2016   5841.0
3    Other Businesses      FY2016    979.0
4   Total Net Revenue      FY2016  18483.0
7  Cost of Goods Sold      FY2016  -9500.0

In [137]:
cleaned_path = "../data/cleaned/Bloomberg_PL_Cleaned.csv"

long_df.to_csv(cleaned_path, index=False)

print(f"Saved: {cleaned_path}")
print("Shape:", long_df.shape)

Saved: ../data/cleaned/Bloomberg_PL_Cleaned.csv
Shape: (249, 3)

In [138]:
pd.read_csv(cleaned_path).head()

            Line Item Fiscal Year    Value
0           Wholesale      FY2016  11663.0
1              Retail      FY2016   5841.0
2    Other Businesses      FY2016    979.0
3   Total Net Revenue      FY2016  18483.0
4  Cost of Goods Sold      FY2016  -9500.0

In [139]:
long_df[long_df["Line Item"].isna()]

Empty DataFrame
Columns: [Line Item, Fiscal Year, Value]
Index: []

In [140]:
lookup_df["Line Item"].tolist()

['Basic EPS',
 'Cost of Goods Sold',
 'Diluted EPS',
 'Distribution and Selling Expense',
 'Dividend Per Share (DPS)',
 'Effective Tax Rate %',
 'Financial Expenses',
 'Financial Income',
 'GROSS PROFIT',
 'General & Administration',
 'Goodwill / Intangible Impairment',
 'Gross Margin %',
 'Income Before Taxes',
 'Income Tax Expense',
 'Less: Minority Interest',
 'Marketing and Point-of-Sale',
 'NET INCOME ATTRIB. TO SHAREHOLDERS',
 'Net Income (Total)',
 'Net Income from Continuing Ops.',
 'Net Income from Disc. Operations',
 'OPERATING PROFIT (EBIT)',
 'Operating Margin %',
 'Other Businesses',
 'Other Operating Income',
 'Retail',
 'Revenue Growth Y/Y',
 'Royalty and Commission Income',
 'Sundry Expenses',
 'Total Net Revenue',
 'Total Other Operating Exp.',
 'Wholesale',
 'Wtd. Avg Shares - Basic (mn)',
 'Wtd. Avg Shares - Diluted (mn)',
 'Revenue',
 'Other Operating Expenses']

In [141]:
long_df["Line Item"].unique().tolist()

['Wholesale',
 'Retail',
 'Other Businesses',
 'Total Net Revenue',
 'Cost of Goods Sold',
 'GROSS PROFIT',
 'Gross Margin %',
 'Royalty and Commission Income',
 'Other Operating Income',
 'Marketing and Point-of-Sale',
 'Distribution and Selling Expense',
 'General & Administration',
 'Sundry Expenses',
 'Total Other Operating Exp.',
 'OPERATING PROFIT (EBIT)',
 'Operating Margin %',
 'Financial Income',
 'Financial Expenses',
 'Income Before Taxes',
 'Income Tax Expense',
 'Effective Tax Rate %',
 'Net Income from Continuing Ops.',
 'Net Income (Total)',
 'Less: Minority Interest',
 'NET INCOME ATTRIB. TO SHAREHOLDERS',
 'Basic EPS',
 'Diluted EPS',
 'Wtd. Avg Shares - Basic (mn)',
 'Wtd. Avg Shares - Diluted (mn)',
 'Dividend Per Share (DPS)',
 'Revenue Growth Y/Y',
 'Net Income from Disc. Operations',
 'Goodwill / Intangible Impairment']